### ISSUE TITLE
「i茅台」预约出错

### ISSUE THREAD

**Issue by loa123** [Sitoi/dailycheckin#331]
「i茅台」
Expecting value: line 1 column 1 (char 0)

所有的内容都按说明搞好了。。预约出错

**Comment by willemsestan** [comment]
+1

**Comment by a5412398** [comment]
----------开始执行「i茅台」签到----------
第 1 个账号: ❌❌❌❌❌
HTTPSConnectionPool(host='itunes.apple.com', port=443): Max retries exceeded with url: /cn/lookup?id=1600482450 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))


是不是脚本挂了，为什么茅台会请求apple.com？  按道理是科学环境，这个是可以访问的

**Comment by loa123** [comment]
docker版总有错误。。换成青龙版就好了
